# Generated by Django 4.2 on 2023-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video',
            field=models.URLField(),
        ),
    ]
